### PR TITLE
Middleware stack cleanup

### PR DESCRIPTION
**Pull request by nicolaslara**
It took a while to figure out what was going on here, but I think this cleans up the call chain to minimize the number of open tasks and threads to the number of context switches in the middleware list. Let me know what you think.

### CODE REVIEW

**Comment by nicolaslara** [comment]
BTW, I used 

```
            # Run the reactor
            import aiomonitor
            with aiomonitor.start_monitor(loop=asyncio.get_event_loop()):
                reactor.run(installSignalHandlers=self.signal_handlers)
``` 

in daphne to monitor the number of async tasks, and `threading.active_count()` to monitor the number of threads. 

This made me realize there might be a problem in which one thread stays open for each request:

```
venv ❯ daphne project.asgi:application
2019-09-03 08:06:56,302 daphne.cli   INFO     Starting server at tcp:port=8000:interface=127.0.0.1
2019-09-03 08:06:56,302 daphne.server INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2019-09-03 08:06:56,302 daphne.server INFO     Configuring endpoint tcp:port=8000:interface=127.0.0.1
2019-09-03 08:06:56,303 daphne.server INFO     Listening on TCP address 127.0.0.1:8000
2019-09-03 08:06:56,325 aiomonitor.monitor INFO     Starting aiomonitor at 127.0.0.1:50101
Current active thread count: 4
127.0.0.1:51540 - - [03/Sep/2019:08:06:59] "GET /sync/" 200 8
Current active thread count: 5
127.0.0.1:51543 - - [03/Sep/2019:08:06:59] "GET /sync/" 200 8
Current active thread count: 6
127.0.0.1:51545 - - [03/Sep/2019:08:07:00] "GET /sync/" 200 8
Current active thread count: 7
127.0.0.1:51547 - - [03/Sep/2019:08:07:01] "GET /sync/" 200 8
Current active thread count: 8
127.0.0.1:51550 - - [03/Sep/2019:08:07:01] "GET /sync/" 200 8
Current active thread count: 9
127.0.0.1:51552 - - [03/Sep/2019:08:07:02] "GET /sync/" 200 8
Current active thread count: 10
127.0.0.1:51554 - - [03/Sep/2019:08:07:04] "GET /async/" 200 8
Current active thread count: 11
127.0.0.1:51557 - - [03/Sep/2019:08:07:04] "GET /async/" 200 8
Current active thread count: 12
127.0.0.1:51559 - - [03/Sep/2019:08:07:05] "GET /async/" 200 8
Current active thread count: 13
127.0.0.1:51561 - - [03/Sep/2019:08:07:05] "GET /async/" 200 8
Current active thread count: 14
127.0.0.1:51564 - - [03/Sep/2019:08:07:06] "GET /async/" 200 8
Current active thread count: 15
127.0.0.1:51566 - - [03/Sep/2019:08:07:07] "GET /async/" 200 8
Current active thread count: 16
127.0.0.1:51568 - - [03/Sep/2019:08:07:09] "GET /sync/" 200 8
Current active thread count: 17
127.0.0.1:51571 - - [03/Sep/2019:08:07:10] "GET /async/" 200 8
^C2019-09-03 08:07:14,697 daphne.server INFO     Killed 0 pending application instances
```

I'm not sure if this is something you're aware of and there is some cleanup that would be triggered later, or if it's a general problem. Also not sure if it's at the level of django, async_to_sync, or daphne.

**Comment by andrewgodwin** [comment]
This is definitely the sort of pattern I was thinking of to minimise jumps between sync and async, yes.

Re: one thread per request - yes, this is currently a fundamental design issue with the way synchronous middleware is wrapped - because we have to keep it open due to the exception handling design, we have to waste a thread per request, which kind of undoes the whole point of async requests. Currently the only way I can think of to solve this is rewriting all Django middleware to be async, which is not exactly a good solution, so I'm waiting until I get time to re-examine the issue, as it may mean we need to substantially change how middleware is called so we can suspend the sync code somehow.

**Comment by nicolaslara** [comment]
> because we have to keep it open due to the exception handling design

hmm... it's still not clear to me why it stays open after the request has been completed, but it seems like the threads get properly reused as needed when the pools start running out of threads, so maybe it's not such a large issue.

**Comment by andrewgodwin** [comment]
Yes, the threadpool will keep the threads alive for re-use - as long as it caps at a certain point, it's fine.

**Pull request merged**
