### PR TITLE
Add happy path tests for async ORM

### PR DESCRIPTION
**Pull request by fcurella**
Preliminary tests that cover  just the happy path of the new methods

### CODE REVIEW

**Comment by carltongibson** [comment]
Thanks for this @fcurella! — I can cherry pick those into the PR tomorrow if @andrewgodwin isn't able to look before then. 

🎁

**Comment by andrewgodwin** [comment]
If you can make flake8 happy I'll gladly merge it in.

Also, given I don't have the spoons to return to this for the near future, should I move it to a branch in django/django or similar so at least others can push to it more easily??

**Comment by carltongibson** [comment]
I'm looking at it now, so I'll correct the flake8 errors and push to your branch Andrew. 

> ... should I move it to... 

No need. Folks can open a PR based on yours, which is how we usually do this. 

Thanks to both of you here. 

🥄🥄

**Comment by carltongibson** [comment]
Hey both — I've pulled this into the PR, done a little bit of work on it, and asked Simon and Mariusz if they can give an initial review. 

https://github.com/django/django/pull/14843

Goal there is get a TODO list together so we can work on it for 4.1. Thanks both of you again! 🚀 
Keep safe.

**Pull request closed without merging**
